spring.application.name=locadora-veiculos

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=locadora;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.sql.init.mode=always
spring.sql.init.separator=GO
spring.sql.init.continue-on-error=false
spring.sql.init.schema-locations=classpath:db/01_schema_sqlserver.sql,\
                                 classpath:db/02_views_sqlserver.sql,\
                                 classpath:db/03_functions_sqlserver.sql,\
                                 classpath:db/04_procedures_sqlserver.sql,\
                                 classpath:db/05_indexes_sqlserver.sql
spring.sql.init.data-locations=classpath:db/06_data_sqlserver.sql

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
